---
apiVersion: submariner.io/v1beta1
kind: Connectivity
metadata:
  name: submariner
spec:
  namespace: "submariner-operator"
  clusterID: "east"
  networkCIDRs: # optional
    services: # optional
      - "192.168.66.0/24"
    cluster: # optional
      - "192.168.67.0/24"
    globalnet: # optional
      - "169.254.0.0/16"
    other/routed: # optional
      - "10.0.0.0/16"   # external network support
  debug: false
  brokers:
    - name: "main-broker"
      apiServer: "192.168.67.110:8443"
      namespace: "submariner-broker"
      secret: "submariner-broker"  # default value
      allowInsecureConnection: false # to allow temporary override on SSL issues like unexpected certificate expiration
  cable: # optional
    driver: "libreswan"
    settings:  # string map
      nat-enabled: "true"   # this overrides auto discovery, or we have "auto/auto-detect/automatic" by default
      debug: "false"
      ikePort: "500"
      nattPort: "4500"
      secret: "submariner-ipsec-psk" # reference to secret, default
  repository: "quay.io/submariner" #default
  version: "$(VERSION)" #default
  imageOverrides:
    submariner-gateway: "......"
    submariner-routeagent: "....."
  status:
    conditions: # like in other standard k8s objects, with the last N conditions

