apiVersion: submariner.io/v1beta1
kind: Broker
metadata:
  name: broker-sample
spec:
  components:
    connectivity: # string map
      enabled: "true"
      cableDriver: "wireguard"
      keyLength: "2048"
      globalnetEnable: "true"
      globalnetClusterSize: "8192"
      globalnetCIDRRange: "169.254.0.0/16"
    service-discovery:
      enable: "true"
      customDomains: "domain1.local,domain2.local"

